# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_CO-c7YcFJkGXEReGWCFvsitPlZ1vLOU
"""

import pytesseract
from PIL import Image


pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

image_path = 'image.png'

img = Image.open(image_path)

extracted_text = pytesseract.image_to_string(img)


print(extracted_text)